[dtr-test]
url="https://dtr-test.pidconsortium.net/"
suffix="objects?query=*"
style="legacy"
types=["PID-BasicInfoType","PID-InfoType","KernelInformationProfile"]

[dtr-pit]
url="https://dtr-pit.pidconsortium.net/"
suffix="objects?query=*"
style="legacy"
types=["PID-BasicInfoType","PID-InfoType","KernelInformationProfile"]