[DTR-Test]
url="https://dtr-test.pidconsortium.net/"
suffix="objects?query=*"
style="legacy"
types=["PID-BasicInfoType","PID-InfoType","KernelInformationProfile"]

[DTR-PIT]
url="https://dtr-pit.pidconsortium.net/"
suffix="objects?query=*"
style="legacy"
types=["PID-BasicInfoType","PID-InfoType","KernelInformationProfile"]

[DTR-Playground]
url="https://dtr-playground.pidconsortium.eu/"
suffix="objects?query=*"
style="eosc"
types=["BasicInfoType","InfoType","KernelInformationProfile"]
units=["Basic-Unit","Derived-Unit"]